Shift the duties of the blj_conf file to the install file.  This is for compatiblity with zsh.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,27 +1,50 @@
 #!/bin/bash
 ###################################################################################
 ##                                                                               ##
-##  This script update user profile to run $BLJ/script/blj_config                ##
-##  If using bash, user_profile=~/.bash_profile (set on 11 as the default val)   ##
-##  If using another env, like zsh, update blj_profile value on line 11 below    ##
-##  If profile exists: save backup wtih ~ appended to name (ex. $blj_profile~    ##
+##  This script updates user profile to                                          ##
+##    include the key variables $BLJ and $BLJ_PROJ                               ##
+##    include the $BLJ/script dir in the $PATH                                   ##
+##                                                                               ##
+##  By default, the script determines the user's profile.                        ##
+##  Optionally, supply the profile to use as an argument.                        ##
+##  ex: ./install ~/.bashrc                                                      ##
 ##                                                                               ##
 ###################################################################################
-export BLJ="$( cd "$( dirname ${BASH_SOURCE[0]} )" && pwd )"
-. $BLJ/script/blj_functions
+BLJ="$( cd "$( dirname ${BASH_SOURCE[0]} )" && pwd )"
 
-user_profile=$(get_default_profile)
-bljDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+# if an arg is given, assume this is the user-profile that user has selected
+# otherwise, determine the user_profile
+user_profile=$1
+if [ ${#user_profile} -eq 0 ]; then
+	. $BLJ/script/blj_functions
+	user_profile=$(get_default_profile)
+	if [ ${#user_profile} -eq 0 ]; then
+		echo "Could not determine user profile. Please supply one, example:"
+		echo "./install ~/.bash_profile"
+		exit 1
+	fi
+fi
 
+# If the profile already exists, back it up.
 if [ ! -f "$user_profile" ]; then
-	printf '%s\n' '#BioLockJ generated bash profile' > $user_profile
+	printf '%s\n' '#BioLockJ generated profile' > $user_profile
 	echo "    Created profile: $user_profile"
 elif [ ! -x "$user_profile" ]; then
 	cp $user_profile $user_profile~
 	echo "    Saved backup:  $user_profile~"
 fi
 
-echo "[ -f $bljDir/script/blj_config ] && . $bljDir/script/blj_config" >> $user_profile
-source $user_profile
+echo 'export BLJ='"$BLJ" >> $user_profile
+
+if [ ${#BLJ_PROJ} -gt 0 ] && [ -d ${BLJ_PROJ} ]; then
+	echo "Found existing "'$BLJ_PROJ: '"$BLJ_PROJ"
+	echo "export BLJ_PROJ=$BLJ_PROJ" >> $user_profile
+else
+	echo 'Setting default BLJ_PROJ=$BLJ/pipelines'
+	echo 'export BLJ_PROJ=$BLJ/pipelines' >> $user_profile
+fi
+
+echo 'export PATH=$PATH:$BLJ/script' >> $user_profile
+
 echo "    Saved profile:  $user_profile"
 echo "BioLockJ installation complete!"
